# Generated by Django 4.1.3 on 2022-12-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategory',
            name='order_number',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
