# Generated by Django 4.1.3 on 2022-12-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transactioncategory_order_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionbase',
            name='month',
            field=models.DateField(default=None, null=True),
        ),
    ]
