# Generated by Django 4.1.3 on 2023-01-09 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionbase',
            name='receipt',
        ),
    ]
